fp = int(input())
fd = int(input())
fs = int(input())
sp = int(input())
sd = int(input())
ss = int(input())
ap = int(input())
ad = int(input())
ash = int(input())
flipkart = int(fp - (fp * fd / 100) + fs)
snapdeal = int(sp - (sp * sd / 100) + ss)
amazon = int(ap - (ap * ad / 100) + ash)
print(f"In Flipkart: Rs.{flipkart}")
print(f"In Snapdeal: Rs.{snapdeal}")
print(f"In Amazon: Rs.{amazon}")
if flipkart <= snapdeal and flipkart <= amazon:
    print("Choose Flipkart")
elif snapdeal <= flipkart and snapdeal <= amazon:
    print("Choose Snapdeal")
